module.exports = {
  preset: 'react-native',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1', // Matches @/...
    '^@components/(.*)$': '<rootDir>/src/components/$1', // @components/...
    '^@constants/(.*)$': '<rootDir>/src/constants/$1', // @constants/...
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1', // @hooks/...
    '^@utils/(.*)$': '<rootDir>/src/utils/$1', // @utils/...
  },
};
